########################################################
# Copyright 2019-2020 program was created VMware, Inc. #
# SPDX-License-Identifier: Apache-2.0                  #
########################################################

{{ if .Values.servingProxy.include }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: serving-proxy
  labels:
    fateMoudle: serving-proxy
    name: {{ .Values.partyName | quote  }}
    partyId: {{ .Values.partyId | quote  }}
    owner: kubefate
    cluster: fate
spec:
  rules:
  - host: {{ .Values.servingProxy.ingerssHost }}
    http:
      paths:
      - path: /
        backend:
          serviceName: serving-proxy
          servicePort: 8059
---
{{ end }}