name: fate-10000
namespace: fate-10000
chartName: fate
chartVersion: v1.4.0
partyId: 10000
registry: ""
pullPolicy: 
persistence: false
modules:
  - rollsite
  - clustermanager
  - nodemanager
  - mysql
  - python
  - client

rollsite: 
  type: NodePort
  nodePort: 30010
  exchange:
    ip: 192.168.1.1
    port: 30000
  partyList:
  - partyId: 9999
    partyIp: 192.168.9.1
    partyPort: 30009
  nodeSelector: {}

nodemanager:
  count: 3                       # nodemanager的数量 默认配置
  sessionProcessorsPerNode: 2    # eggroll.session.processors.per.node配置
  list:                          # 自定义nodemanager配置 与count同时生效说
  - name: nodemanager
    nodeSelector: {}
    sessionProcessorsPerNode: 2
    subPath: "nodemanager"
    existingClaim: ""
    storageClass: "nodemanager"
    accessMode: ReadWriteOnce
    size: 1Gi

python:
  fateflowType: NodePort
  fateflowNodePort: 30109
  nodeSelector: {}

mysql: 
  nodeSelector: {}
  ip: mysql
  port: 3306
  database: eggroll_meta
  user: fate
  password: fate_dev
  subPath: ""
  existingClaim: ""
  storageClass: ""
  accessMode: ReadWriteOnce
  size: 1Gi

# 如果不安装MySQL的时候配置
externalMysqlIp: mysql
externalMysqlPort: 3306
externalMysqlDatabase: eggroll_meta
externalMysqlUser: fate
externalMysqlPassword: fate_dev


servingIp: 192.168.9.1
servingPort: 30209